# Generated by Django 4.1.10 on 2023-10-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "desired_skills",
                    models.JSONField(
                        blank=True, null=True, verbose_name="DesiredSkills"
                    ),
                ),
                (
                    "field",
                    models.JSONField(blank=True, null=True, verbose_name="field"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OP", "Open to contributions"),
                            ("AO", "Active and Open"),
                            ("AC", "Active"),
                            ("I", "Inactive"),
                            ("C", "Completed"),
                            ("AR", "Archived"),
                            ("OH", "On-Hold"),
                        ],
                        default="OP",
                        max_length=10,
                        null=True,
                        verbose_name="status",
                    ),
                ),
                ("starting_date", models.DateField()),
                ("finishing_date", models.DateField(null=True)),
            ],
        ),
    ]
