# Generated by Django 4.1.10 on 2023-10-07 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsersProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.TextField(verbose_name="role")),
                ("scope", models.TextField(verbose_name="role")),
                (
                    "project_id",
                    models.ManyToManyField(
                        related_name="users_projects", to="Projects.project"
                    ),
                ),
                (
                    "user_id",
                    models.ManyToManyField(
                        related_name="users_projects", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
