# Generated by Django 4.1.10 on 2023-10-07 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Projects", "0003_joiningrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="field",
            field=models.CharField(max_length=100, verbose_name="field"),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("OP", "Open to contributions"),
                    ("AO", "Active and Open"),
                    ("AC", "Active"),
                    ("I", "Inactive"),
                    ("C", "Completed"),
                    ("AR", "Archived"),
                    ("OH", "On-Hold"),
                ],
                default="OP",
                max_length=100,
                null=True,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="usersprojects",
            name="project_id",
            field=models.ManyToManyField(
                related_name="projects", to="Projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="usersprojects",
            name="user_id",
            field=models.ManyToManyField(
                related_name="users", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
