# Generated by Django 4.1.10 on 2023-10-07 23:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Projects", "0006_remove_usersprojects_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.ManyToManyField(
                related_name="owner", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
