# Generated by Django 4.1.10 on 2023-10-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Projects", "0007_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="joiningrequests",
            name="desired_role",
            field=models.CharField(
                default="", max_length=100, verbose_name="desired_role"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("OP", "Open to contributions"),
                    ("AC", "Active"),
                    ("C", "Completed"),
                    ("AR", "Archived"),
                    ("OH", "On-Hold"),
                ],
                default="OP",
                max_length=100,
                null=True,
                verbose_name="status",
            ),
        ),
    ]
