# Generated by Django 4.1.10 on 2023-10-08 00:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Projects", "0008_joiningrequests_desired_role_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joiningrequests",
            name="project_id",
            field=models.ManyToManyField(related_name="project", to="Projects.project"),
        ),
        migrations.AlterField(
            model_name="joiningrequests",
            name="user_id",
            field=models.ManyToManyField(
                related_name="user", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
