# Generated by Django 4.1.10 on 2023-10-08 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Projects", "0009_alter_joiningrequests_project_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joiningrequests",
            name="project_id",
        ),
        migrations.RemoveField(
            model_name="joiningrequests",
            name="user_id",
        ),
        migrations.AddField(
            model_name="joiningrequests",
            name="project_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="Projects.project",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="joiningrequests",
            name="user_id",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
