# Generated by Django 4.1.10 on 2023-10-08 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0003_user_defaultsummary_user_experience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
    ]
