# Generated by Django 4.1.10 on 2023-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Users", "0004_user_is_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="user",
            name="seeking_fields",
        ),
        migrations.RemoveField(
            model_name="user",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="user",
            name="working_availability",
        ),
        migrations.AddField(
            model_name="profile",
            name="experience",
            field=models.JSONField(blank=True, null=True, verbose_name="Esperience"),
        ),
        migrations.AddField(
            model_name="profile",
            name="seeking_fields",
            field=models.JSONField(blank=True, null=True, verbose_name="SeekingSkills"),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.JSONField(blank=True, null=True, verbose_name="skills"),
        ),
        migrations.AddField(
            model_name="profile",
            name="working_availability",
            field=models.DateField(null=True),
        ),
    ]
