version: '3.9'

services:
  traefik:
    container_name: traefik
    image: ${TRAEFIK}
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proxy.rule=Host(`traefik.opencommunity.work`)"
      - "traefik.http.routers.proxy.entrypoints=web"
      - "traefik.http.routers.proxy.service=api@internal"
      - "traefik.http.services.proxy.loadbalancer.server.port=8080"


  app:
    container_name: django-app
    build:
      context: ../../
      dockerfile: ${DOCKERFILE_PATH}
    image: &app app
    restart: always
    env_file: &envfile
      - ../../Envs/Production/variables.env
    ports:
      - "8000:8000"
    volumes:
      - ../../Apps:/App/Apps
      - ../../staticfiles:/App/staticfiles
      - ../../Project:/App/Project
      - ../../Envs/Production/django_settings.py:/App/Envs/Production/django_settings.py
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.opencommunity.work`)"
      - "traefik.http.routers.api.service=api"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.routers.api.entrypoints=web"

  front:
    container_name: front-app
    image: alejandroacho/space-apps-2023
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`front.opencommunity.work`)"
      - "traefik.http.routers.front.service=front"
      - "traefik.http.services.front.loadbalancer.server.port=3000"
      - "traefik.http.routers.front.entrypoints=web"
