# API and dashboard configuration
api:
  # Dashboard
  dashboard: true
  insecure: true

# Docker configuration backend
providers:
  docker:
    exposedByDefault: false

# Needed for healthy check
ping: {}

# Traefik Logging
log:
  level: ERROR

# Entrypoint
entryPoints:
  web:
    address: ":80"
